# Generated by Django 2.1.3 on 2018-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('auhtor', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=50)),
            ],
        ),
    ]
